export const formTitle = "Reach out to us!"
export const inputNameText = "Your name*"
export const inputEmailText = "Your email*"
export const inputMessageText = "Your message*"
export const buttonText = "Send message"